const express = require('express')
const router = express.Router()
const empRoute = require('./modules/employess.route')
const userRoute = require('./modules/systemusers.route')
const officersRoute = require('./modules/officers.route')
const documentRoute = require('./modules/document_type.route')
const incidentRoute = require('./modules/incident_title.route')
const penaltyRoute = require('./modules/penalty_type.route')
const settingsRoute = require('./modules/settings.route')
const notificationsRoute = require('./modules/notifications.route')
const auditlogRoute = require('./modules/audit_log.route')
const casesRoute = require('./modules/cases.route')

router.use('/employees',empRoute)
router.use('/system_users',userRoute)
router.use('/officers',officersRoute)
router.use('/document_type',documentRoute)
router.use('/incident_title',incidentRoute)
router.use('/penalty_type',penaltyRoute)
router.use('/settings',settingsRoute)
router.use('/notifications',notificationsRoute)
router.use('/audit_log',auditlogRoute)
router.use('/cases',casesRoute)

module.exports = router